/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as MenusRouteImport } from './routes/menus'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GroceriesRouteImport } from './routes/groceries'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenusIndexRouteImport } from './routes/menus/index'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'
import { Route as MenusIdRouteImport } from './routes/menus/$id'
import { Route as EditIdRouteImport } from './routes/edit/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusRoute = MenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceriesRoute = GroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusIndexRoute = MenusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenusRoute,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusIdRoute = MenusIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MenusRoute,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/groceries': typeof GroceriesRoute
  '/import': typeof ImportRoute
  '/menus': typeof MenusRouteWithChildren
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/edit/$id': typeof EditIdRoute
  '/menus/$id': typeof MenusIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/menus/': typeof MenusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/groceries': typeof GroceriesRoute
  '/import': typeof ImportRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/edit/$id': typeof EditIdRoute
  '/menus/$id': typeof MenusIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/menus': typeof MenusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/groceries': typeof GroceriesRoute
  '/import': typeof ImportRoute
  '/menus': typeof MenusRouteWithChildren
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/edit/$id': typeof EditIdRoute
  '/menus/$id': typeof MenusIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/menus/': typeof MenusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/groceries'
    | '/import'
    | '/menus'
    | '/plan'
    | '/settings'
    | '/edit/$id'
    | '/menus/$id'
    | '/recipes/$id'
    | '/menus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/groceries'
    | '/import'
    | '/plan'
    | '/settings'
    | '/edit/$id'
    | '/menus/$id'
    | '/recipes/$id'
    | '/menus'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/groceries'
    | '/import'
    | '/menus'
    | '/plan'
    | '/settings'
    | '/edit/$id'
    | '/menus/$id'
    | '/recipes/$id'
    | '/menus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  GroceriesRoute: typeof GroceriesRoute
  ImportRoute: typeof ImportRoute
  MenusRoute: typeof MenusRouteWithChildren
  PlanRoute: typeof PlanRoute
  SettingsRoute: typeof SettingsRoute
  EditIdRoute: typeof EditIdRoute
  RecipesIdRoute: typeof RecipesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus': {
      id: '/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groceries': {
      id: '/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof GroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus/': {
      id: '/menus/'
      path: '/'
      fullPath: '/menus/'
      preLoaderRoute: typeof MenusIndexRouteImport
      parentRoute: typeof MenusRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus/$id': {
      id: '/menus/$id'
      path: '/$id'
      fullPath: '/menus/$id'
      preLoaderRoute: typeof MenusIdRouteImport
      parentRoute: typeof MenusRoute
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MenusRouteChildren {
  MenusIdRoute: typeof MenusIdRoute
  MenusIndexRoute: typeof MenusIndexRoute
}

const MenusRouteChildren: MenusRouteChildren = {
  MenusIdRoute: MenusIdRoute,
  MenusIndexRoute: MenusIndexRoute,
}

const MenusRouteWithChildren = MenusRoute._addFileChildren(MenusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  GroceriesRoute: GroceriesRoute,
  ImportRoute: ImportRoute,
  MenusRoute: MenusRouteWithChildren,
  PlanRoute: PlanRoute,
  SettingsRoute: SettingsRoute,
  EditIdRoute: EditIdRoute,
  RecipesIdRoute: RecipesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
